---
- name: Configure the timezone
  become: yes
  template:
    src: timezone.j2
    dest: /etc/timezone

- name: Symlink localtime configuration
  become: yes
  file:
    src: "/usr/share/zoneinfo/{{ locale_timezone }}"
    dest: /etc/localtime
    state: link
    force: yes
    backup: yes
